name: CI

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.71.0
        default: true
        profile: minimal
        components: clippy

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rustfmt

    - name: cargo fmt
      run: cargo +nightly fmt -- --check

    - name: cargo clippy
      run: cargo clippy --all --all-targets -- -D clippy::all

    - name: cargo test
      run: cargo test --all --all-targets
